version: '3.7'

services:
  db:
    image: postgres:12-alpine
    container_name: agh-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - agh_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: agh-redis
    restart: on-failure
    ports:
      - ${REDIS_PORT}:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - agh_redis_data:/data

  agh-bot:
    container_name: 'agh-bot'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: agh-bot
      # target: local
    environment:
      - CRYPTO_KEY=${CRYPTO_KEY}
      - CRYPTO_IV=${CRYPTO_IV}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_DB=agh_db
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - TOKEN=${TOKEN}
    restart: on-failure
    depends_on:
      - db
      - redis
    ports:
      - '3000:3000'
  
  agh-member-history:
    container_name: 'agh-member-history'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: member-history
    environment:
      - CRYPTO_KEY=${CRYPTO_KEY}
      - CRYPTO_IV=${CRYPTO_IV}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_DB=agh_db
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - TOKEN=${TOKEN}
    restart: on-failure
    depends_on:
      - db
      - redis
    ports:
      - '3001:3000'

volumes:
  agh_postgres_data:
    driver: local
  agh_redis_data:
    driver: local
